version: "3.3"
services:
  run:
    volumes:
      - "${PWD}:/src"
    image: openapitools/openapi-generator-cli
    command: "generate  -i https://github.com/ethereum/beacon-APIs/releases/download/v2.4.2/beacon-node-oapi.json -g python-fastapi --skip-validate-spec  -o /src/auto"
